window.env = {
  "ACLOCAL_PATH": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\share\\aclocal;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\share\\aclocal",
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\IqbalHossain\\AppData\\Roaming",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\LOCAL\\crashpad_12188_ETRKVYDMLLEPAFGM",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "BDL-PF1B3E4H",
  "COMSPEC": "C:\\Windows\\system32\\cmd.exe",
  "CONFIG_SITE": "C:/Users/IqbalHossain/AppData/Local/Programs/Git/etc/config.site",
  "DISPLAY": "needs-to-be-defined",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\Windows\\notepad.exe",
  "EXEPATH": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\IqbalHossain",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\IqbalHossain",
  "HOSTNAME": "BDL-PF1B3E4H",
  "INFOPATH": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\local\\info;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\share\\info;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\local\\info;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\share\\info;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\info;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\share\\info",
  "INIT_CWD": "C:\\Users\\IqbalHossain\\Desktop\\ivideo",
  "KEY": "AIzaSyBd4SOTYQlu-tCyW6PsPmt0_1XSUB-WCoY&type",
  "LANG": "en_US.UTF-8",
  "LC_CTYPE": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\IqbalHossain\\AppData\\Local",
  "LOGONSERVER": "\\\\BDL-PF1B3E4H",
  "MANPATH": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\local\\man;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\share\\man;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\local\\man;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\share\\man;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\man;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\share\\man",
  "MINGW_CHOST": "x86_64-w64-mingw32",
  "MINGW_PACKAGE_PREFIX": "mingw-w64-x86_64",
  "MINGW_PREFIX": "C:/Users/IqbalHossain/AppData/Local/Programs/Git/mingw64",
  "MSYSTEM": "MINGW64",
  "MSYSTEM_CARCH": "x86_64",
  "MSYSTEM_CHOST": "x86_64-w64-mingw32",
  "MSYSTEM_PREFIX": "C:/Users/IqbalHossain/AppData/Local/Programs/Git/mingw64",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"predeploy\"],\"original\":[\"deploy\"]}",
  "npm_config_bin_links": "true",
  "npm_config_cache": "C:\\Users\\IqbalHossain\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm",
  "npm_config_ignore_optional": "",
  "npm_config_ignore_scripts": "",
  "npm_config_init_license": "MIT",
  "npm_config_init_module": "C:\\Users\\IqbalHossain\\.npm-init.js",
  "npm_config_init_version": "1.0.0",
  "npm_config_local_prefix": "C:\\Users\\IqbalHossain\\Desktop\\ivideo",
  "npm_config_metrics_registry": "https://registry.yarnpkg.com",
  "npm_config_node_gyp": "C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm",
  "npm_config_registry": "https://registry.yarnpkg.com",
  "npm_config_save_prefix": "^",
  "npm_config_strict_ssl": "true",
  "npm_config_userconfig": "C:\\Users\\IqbalHossain\\.npmrc",
  "npm_config_user_agent": "yarn/1.22.19 npm/? node/v18.14.2 win32 x64",
  "npm_config_version_commit_hooks": "true",
  "npm_config_version_git_message": "v%s",
  "npm_config_version_git_sign": "",
  "npm_config_version_git_tag": "true",
  "npm_config_version_tag_prefix": "v",
  "npm_execpath": "C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_browserslist_production_1": "not dead",
  "npm_package_browserslist_production_2": "not op_mini all",
  "npm_package_dependencies_axios": "^0.27.2",
  "npm_package_dependencies_bootstrap": "^5.2.0",
  "npm_package_dependencies_dotenv": "^16.0.3",
  "npm_package_dependencies_gitignore": "^0.7.0",
  "npm_package_dependencies_react": "^18.2.0",
  "npm_package_dependencies_react_dom": "^18.2.0",
  "npm_package_dependencies_react_dotenv": "^0.1.3",
  "npm_package_dependencies_react_scripts": "5.0.1",
  "npm_package_description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
  "npm_package_devDependencies_gh_pages": "^5.0.0",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_homepage": "https://jsiqbal.github.io/ivideo",
  "npm_package_json": "C:\\Users\\IqbalHossain\\Desktop\\ivideo\\package.json",
  "npm_package_name": "video_browser",
  "npm_package_private": "true",
  "npm_package_readmeFilename": "README.md",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_deploy": "gh-pages -d build",
  "npm_package_scripts_eject": "react-scripts eject",
  "npm_package_scripts_predeploy": "npm run build",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_package_scripts_test": "react-scripts test",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "OLDPWD": "C:/Users/IqbalHossain/Desktop",
  "OneDrive": "C:\\Users\\IqbalHossain\\OneDrive - ADA Global",
  "OneDriveCommercial": "C:\\Users\\IqbalHossain\\OneDrive - ADA Global",
  "ORIGINAL_PATH": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\bin;C:\\Users\\IqbalHossain\\bin;C:\\softwares\\flutter\\flutter\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\nodejs;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn;C:\\Program Files\\dotnet;C:\\Users\\IqbalHossain\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\cmd;C:\\Users\\IqbalHossain\\AppData\\Local\\gitkraken\\bin",
  "ORIGINAL_TEMP": "C:/Users/IQBALH~1/AppData/Local/Temp",
  "ORIGINAL_TMP": "C:/Users/IQBALH~1/AppData/Local/Temp",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "PATH": "C:\\Users\\IqbalHossain\\Desktop\\ivideo\\node_modules\\.bin;C:\\Users\\IqbalHossain\\Desktop\\node_modules\\.bin;C:\\Users\\IqbalHossain\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\IQBALH~1\\AppData\\Local\\Temp\\yarn--1681719862110-0.6375686086043693;C:\\Users\\IqbalHossain\\Desktop\\ivideo\\node_modules\\.bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Yarn\\Data\\link\\node_modules\\.bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Yarn\\bin;C:\\Program Files\\libexec\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Users\\IqbalHossain\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\local\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\bin;C:\\Users\\IqbalHossain\\bin;C:\\softwares\\flutter\\flutter\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\nodejs;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn;C:\\Program Files\\dotnet;C:\\Users\\IqbalHossain\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\IqbalHossain\\AppData\\Roaming\\npm;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\cmd;C:\\Users\\IqbalHossain\\AppData\\Local\\gitkraken\\bin;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\bin\\vendor_perl;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\bin\\core_perl",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC",
  "PKG_CONFIG_PATH": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\lib\\pkgconfig;C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\mingw64\\share\\pkgconfig",
  "PKG_CONFIG_SYSTEM_INCLUDE_PATH": "C:/Users/IqbalHossain/AppData/Local/Programs/Git/mingw64/include",
  "PKG_CONFIG_SYSTEM_LIBRARY_PATH": "C:/Users/IqbalHossain/AppData/Local/Programs/Git/mingw64/lib",
  "PLINK_PROTOCOL": "ssh",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 142 Stepping 12, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "8e0c",
  "ProgramData": "C:\\ProgramData",
  "PROGRAMFILES": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "PWD": "C:/Users/IqbalHossain/Desktop/ivideo",
  "SESSIONNAME": "Console",
  "SHELL": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
  "SHLVL": "3",
  "SSH_ASKPASS": "C:/Users/IqbalHossain/AppData/Local/Programs/Git/mingw64/bin/git-askpass.exe",
  "SYSTEMDRIVE": "C:",
  "SYSTEMROOT": "C:\\Windows",
  "TEMP": "C:\\Users\\IQBALH~1\\AppData\\Local\\Temp",
  "TERM": "xterm",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.77.3",
  "TMP": "C:\\Users\\IQBALH~1\\AppData\\Local\\Temp",
  "TMPDIR": "C:\\Users\\IQBALH~1\\AppData\\Local\\Temp",
  "USERDOMAIN": "AzureAD",
  "USERDOMAIN_ROAMINGPROFILE": "AzureAD",
  "USERNAME": "IqbalHossain",
  "USERPROFILE": "C:\\Users\\IqbalHossain",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\IqbalHossain\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-e99f258a66-sock",
  "WINDIR": "C:\\Windows",
  "YARN_WRAP_OUTPUT": "false",
  "ZES_ENABLE_SYSMAN": "1"
};